jenkins/piwind.groovy
oasislmf.json

Keys in oasislmf.json led to errors. Replaced contents of oasislmf.json with oasislmf-oed.json.

Replace oasislmf.json with oasislmf-oed.json

---

analysis_settings.json
meta-data/model_settings.json
oasislmf.json

Adds default group fields to PiWind model to illustrate functionality of changes in MDK re: https://github.com/OasisLMF/OasisLMF/pull/527

Add group fields

---

jenkins/piwind.groovy

Update build script for oasis_platform change

Update CI script param

---

docker/Dockerfile.piwind_worker
docker/oasislmf_deploy.json

added a docker file and oasislmf.json for a built image to be deployed

docker image updates

---

meta-data/chunking_configuration.json
meta-data/model_settings.json
meta-data/scaling_configuration.json

* The `number_of_events` value is required for dynamic chunking in platform-2.0
* Added `scaling_configuration.json` and `chunking_configuration.json` files

 Add Meta-data for platform v2

---

src/exposure_modification/exposure_pre_analysis_example.py

Fix `exposure_pre_analysis_example.py` for loading parquet location files

Fix parquet loc file loading

---

.github/workflows/run_mdk.yml
.github/workflows/test.yml
tests/run_mdk.py

Test CI from external PR 

---

tests/test_piwind_integration.py

An extra wait is needed for the model to become ready (not just the server)

Add wait for model to self reg

---

.github/workflows/integration.yml
.github/workflows/run_mdk.yml
.github/workflows/test.yml
docker/Dockerfile.piwind_worker

Add ods package build options to piwind testing workflows 

---

docker/Dockerfile.piwind_worker

* only uninstall install wheel package if given, rather than a full reinstall

only reinstall local packages not everything

---

.github/workflows/integration.yml

Test fix for docker logging

---

analysis_settings.json
analysis_settings_ord.json
meta-data/model_settings.json
tests/ci/FM_analysis_settings.json
tests/ci/GUL_analysis_settings.json
tests/ci/ORD_csv_analysis_settings.json
tests/ci/ORD_parquet_analysis_settings.json
tests/ci/RI_analysis_settings.json

From ods-tools==3.0.4 and on analysis / model settings are versioned, add that field to files in piwind

Update settings file to include base version 3

---

.github/workflows/test.yml

Fix CI script

---

.github/workflows/integration.yml
docker/Dockerfile.piwind_server

Fix missing ods-tools package update in server image

Build server and worker with CI assests

---

tests/modelcheck.py

CI issue - Fix wait for model to reg

---

.github/workflows/integration.yml

Install pytest requirements from main piwind branch to avoid dependency problems

fix requ install

---

docker/plat2-v2.s3.docker-compose.yml

Added `OASIS_AWS_LOCATION` to S3 testing compose to test that files are store correctly

Add AWS location to compose file

---

.github/workflows/run_mdk.yml
tests/run_mdk.py

Fix MDK install test in CI

---

.github/workflows/run_mdk.yml
tests/run_mdk.py

Adapt run_mdk test to new path for RI files from run_directory to input
https://github.com/OasisLMF/OasisLMF/pull/1534

Fix test as Ri moved to input

---

.github/workflows/integration.yml
docker/plat2-v2.docker-compose.yml
docker/plat2-v2.s3.docker-compose.yml
docker/plat2.docker-compose.yml
tests/conftest.py
tests/modelcheck.py

Fix for testing, issue from https://github.com/OasisLMF/OasisPlatform/issues/1195
The V2 runs are running with a single chunk which is not a realistic check. Default to setting the chunks to number of cpu on test vm.  
fails correctly with version `2.4.1` where the bug is occurring 
https://github.com/OasisLMF/OasisPlatform/actions/runs/14489384487/job/40642393486
```
Traceback (most recent call last):
File "/home/worker/src/model_execution_worker/distributed_tasks.py", line 885, in run
return fn(self, params, *args, analysis_id=analysis_id, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/worker/src/model_execution_worker/distributed_tasks.py", line 1000, in generate_losses_chunk
OasisManager().generate_losses_partial(**chunk_params)
File …
```

Fix v2 image testing
